name: livraison
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.5.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  http: ^1.2.2
  shared_preferences: ^2.0.0
  image_picker: ^0.8.7+4
  fl_chart: ^0.69.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  mockito: ^5.0.0
  build_runner: ^2.1.0  # Ajout de build_runner
  test: ^1.20.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
